import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Directions_home from '@/components/directions/views/directions/directions'
import SpeedDisplay from '@/components/speed_display/speed_display'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <Get_directions/> */}
        < Directions_home />
        <SpeedDisplay/>
      </main>
    </>
  )
}
